// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function CheckLogin(arg1:string):Promise<Record<string, any>>;

export function DeleteFile(arg1:string):Promise<boolean>;

export function GetConfig():Promise<config.AppConfig>;

export function ListFiles(arg1:string):Promise<Array<main.FileInfo>>;

export function Log(arg1:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function SaveConfig(arg1:Record<string, any>):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function StartTask(arg1:Record<string, any>):Promise<string>;

export function StopTask():Promise<void>;
