// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function CheckLogin(arg1:string):Promise<Record<string, any>>;

export function DeleteArchive(arg1:string):Promise<boolean>;

export function GetArchives():Promise<Array<main.ArchiveItem>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetLanguagePack(arg1:string):Promise<config.LanguagePack>;

export function GetTotalStats():Promise<number>;

export function Log(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function ResetTotalStats():Promise<void>;

export function RunRegistration(arg1:Record<string, any>):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;

export function StopRegistration():Promise<void>;

export function TestAPIPushURL(arg1:string):Promise<boolean>;

export function UpdateConfig(arg1:config.AppConfig):Promise<boolean>;
