// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLogin(arg1) {
  return window['go']['main']['App']['CheckLogin'](arg1);
}

export function DeleteArchive(arg1) {
  return window['go']['main']['App']['DeleteArchive'](arg1);
}

export function GetArchives() {
  return window['go']['main']['App']['GetArchives']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLanguagePack(arg1) {
  return window['go']['main']['App']['GetLanguagePack'](arg1);
}

export function GetTotalStats() {
  return window['go']['main']['App']['GetTotalStats']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function ResetTotalStats() {
  return window['go']['main']['App']['ResetTotalStats']();
}

export function RunRegistration(arg1) {
  return window['go']['main']['App']['RunRegistration'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function StopRegistration() {
  return window['go']['main']['App']['StopRegistration']();
}

export function TestAPIPushURL(arg1) {
  return window['go']['main']['App']['TestAPIPushURL'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
